plugins {
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom'
    id "de.maxhenkel.cursegradle" version "1.5.+"
    id "com.modrinth.minotaur" version "2.+"
}

repositories {
    maven {
        name = 'TerraformersMC'
        url = 'https://maven.terraformersmc.com/releases/'
        content {
            includeGroup 'com.terraformersmc'
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    compileOnly "com.terraformersmc:modmenu:${mod_menu_version}"
    localRuntime "com.terraformersmc:modmenu:${mod_menu_version}"
}

loom {
    def aw = project(":Common").file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    runs {
        client {
            client()
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("runs/client")
        }
        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
            runDir("runs/server")
        }
    }
}

curseforge {

    def curseforgeToken = System.getenv("CURSEFORGE_TOKEN")
    if (curseforgeToken) {
        apiKey = curseforgeToken
    }

    project {
        id = project.curseforge_project_id
        changelogType = "markdown"
        changelog = project.ext.changelog
        releaseType = project.release_type
        "${project.supported_versions}".split(',').each {
            addGameVersion "${it}"
        }
        addGameVersion "Fabric"
        addGameVersion "Java ${java_version}"

        mainArtifact(jar) {
            displayName = "[Fabric] Transmog $project.mod_version+$project.minecraft_version"
        }
        addArtifact(sourcesJar)
        relations {
            requiredDependency("fabric-api")
            optionalDependency("modmenu")
        }

        afterEvaluate {
            uploadTask.dependsOn("jar")
        }
    }

    options {
        forgeGradleIntegration = false
    }
}

modrinth {
    projectId = project.modrinth_project_id
    versionName = "[Fabric] Transmog $project.mod_version+$project.minecraft_version"
    versionNumber = "fabric-${project.mod_version}+${project.minecraft_version}"
    versionType = project.release_type
    changelog = project.ext.changelog
    uploadFile = jar
    additionalFiles = [sourcesJar]
    gameVersions = "${project.supported_versions}".split(',') as List<String>
    loaders = ["fabric"]
    dependencies {
        required.project "fabric-api"
        optional.project "modmenu"
    }
}