# Project
archives_base_name=transmog
group=com.hidoni.transmog
java_version=21

# Common
minecraft_version=1.21.11
minecraft_version_range=[1.21.11,1.21.12)
mod_name=Transmog
mod_author=Hidoni
mod_id=transmog
mod_version=1.7.2
description=Change the appearance of your items without modifying their behavior/stats!
mod_credits=Junshengxie - Chinese Translation, elinka47 - Japanese Translation, TheAnaxMan - Russian Translation
license=MIT
neo_form_version=1.21.11-20251209.172050
parchment_minecraft_version=1.21.11
parchment_mappings_version=2025.12.20
mixinextras_version=0.5.0

# Forge
forge_version=61.0.8
forge_loader_version_range=[61,)

# Fabric
fabric_version=0.141.3+1.21.11
fabric_loader_version=0.18.4
mod_menu_version=17.0.0-beta.2

# NeoForge
neoforge_version=21.11.38-beta

# Publishing
curseforge_project_id=848032
modrinth_project_id=Th33t82F
release_type=release
supported_versions=1.21.11

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false