# Project
archives_base_name=transmog
group=com.hidoni.transmog
java_version=21

# Common
minecraft_version=1.21.8
minecraft_version_range=[1.21.8,1.21.9)
mod_name=Transmog
mod_author=Hidoni
mod_id=transmog
mod_version=1.7.0
description=Change the appearance of your items without modifying their behavior/stats!
mod_credits=Junshengxie - Chinese Translation
license=MIT
neo_form_version=1.21.8-20250717.133445
parchment_minecraft_version=1.21.8
parchment_mappings_version=2025.07.20
mixinextras_version=0.4.1

# Forge
forge_version=58.0.5
forge_loader_version_range=[58,)

# Fabric
fabric_version=0.131.0+1.21.8
fabric_loader_version=0.17.2
mod_menu_version=15.0.0-beta.3

# NeoForge
neoforge_version=21.8.29

# Publishing
curseforge_project_id=848032
modrinth_project_id=Th33t82F
release_type=release
supported_versions=1.21.8

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false