# Project
archives_base_name=transmog
group=com.hidoni.transmog
java_version=21

# Common
minecraft_version=1.21.3
minecraft_version_range=[1.21.3,1.21.4)
mod_name=Transmog
mod_author=Hidoni
mod_id=transmog
mod_version=1.6.0
description=Change the appearance of your items without modifying their behavior/stats!
mod_credits=Junshengxie - Chinese Translation
license=MIT
neo_form_version=1.21.3-20241023.131943
parchment_minecraft_version=1.21.3
parchment_mappings_version=2024.12.07
mixinextras_version=0.4.1

# Forge
forge_version=53.0.33
forge_loader_version_range=[53,)

# Fabric
fabric_version=0.112.1+1.21.3
fabric_loader_version=0.16.9
mod_menu_version=12.0.0

# NeoForge
neoforge_version=21.3.58
neoforge_loader_version_range=[4,)

# Publishing
curseforge_project_id=848032
modrinth_project_id=Th33t82F
release_type=release
supported_versions=1.21.3

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false