plugins {
    id 'multiloader-loader'
    id "de.maxhenkel.cursegradle" version "1.5.+"
    id "com.modrinth.minotaur" version "2.+"
    id 'net.minecraftforge.gradle' version '[7.0.17,8)'
    id 'net.minecraftforge.jarjar' version '0.2.3'
}

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
}

minecraft {
    def ats = [file('src/main/resources/META-INF/accesstransformer.cfg'), project(":Common").file("src/main/resources/META-INF/common_accesstransformer.cfg")].findAll {it.exists()}
    if (!ats.isEmpty()) {
        accessTransformers = files(ats.toArray(new File[0]))
    }

    runs {
        configureEach {
            args "-mixin.config=mixins.${mod_id}.common.json"
            args "-mixin.config=mixins.${mod_id}.forge.json"
        }

        register('client') {
            workingDir = layout.projectDirectory.dir('runs/client')
        }

        register('server') {
            workingDir = layout.projectDirectory.dir('runs/server')
        }

        register('clientData') {
            workingDir = layout.projectDirectory.dir('runs/data')
            args '--mod', mod_id, '--client', '--output', file('../Common/src/generated/resources/'), '--existing', file('src/main/resources/'), '--existing', file('/../Common/src/main/resources')
        }
    }
}

jarJar.register()
tasks.named('jar') {
    archiveClassifier = 'slim'
    manifest {
        attributes([
                "MixinConfigs": "mixins.transmog.common.json,mixins.transmog.forge.json"
        ])
    }
    finalizedBy(tasks.jarJar)
}

tasks.named('jarJar') {
    archiveClassifier = null
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${minecraft_version}-${forge_version}")

    annotationProcessor 'net.minecraftforge:eventbus-validator:7.0-beta.7'

    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:${mixinextras_version}"))
    jarJar("io.github.llamalad7:mixinextras-forge:${mixinextras_version}")
}

sourceSets.each {
    def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
    it.output.resourcesDir = dir
    it.java.destinationDirectory = dir
}

curseforge {

    def curseforgeToken = System.getenv("CURSEFORGE_TOKEN")
    if (curseforgeToken) {
        apiKey = curseforgeToken
    }

    project {
        id = project.curseforge_project_id
        changelogType = "markdown"
        changelog = project.ext.changelog
        releaseType = project.release_type
        "${project.supported_versions}".split(',').each {
            addGameVersion "${it}"
        }
        addGameVersion "Forge"
        addGameVersion "Java ${java_version}"
        addGameVersion "Client"
        addGameVersion "Server"

        mainArtifact(tasks.jarJar) {
            displayName = "[Forge] Transmog $project.mod_version+$project.minecraft_version"
        }
        addArtifact(sourcesJar)
    }
}

modrinth {
    projectId = project.modrinth_project_id
    versionName = "[Forge] Transmog $project.mod_version+$project.minecraft_version"
    versionNumber = "forge-${project.mod_version}+${project.minecraft_version}"
    versionType = project.release_type
    changelog = project.ext.changelog
    uploadFile = tasks.jarJar
    additionalFiles = [sourcesJar]
    gameVersions = "${project.supported_versions}".split(',') as List<String>
    loaders = ["forge"]
}

sourceSets.each {
    def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
    it.output.resourcesDir = dir
    it.java.destinationDirectory = dir
}
