plugins {
    id 'multiloader-loader'
    id "com.matthewprenger.cursegradle" version "1.4.+"
    id "com.modrinth.minotaur" version "2.+"
    id 'net.minecraftforge.gradle' version '[6.0.24,6.2)'
    id 'org.spongepowered.mixin' version '0.7-SNAPSHOT'
}

minecraft {
    mappings channel: 'official', version: minecraft_version

    copyIdeResources = true

    reobf false

    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformer = at
    }

    runs {
        client {
            workingDirectory file('runs/client')
            ideaModule "${rootProject.name}.${project.name}.main"
            taskName 'Client'
            arg "-mixin.config=mixins.${mod_id}.common.json"
            arg "-mixin.config=mixins.${mod_id}.forge.json"
            mods {
                modClientRun {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory file('runs/server')
            ideaModule "${rootProject.name}.${project.name}.main"
            taskName 'Server'
            arg "-mixin.config=mixins.${mod_id}.common.json"
            arg "-mixin.config=mixins.${mod_id}.forge.json"
            mods {
                modServerRun {
                    source sourceSets.main
                }
            }
        }

        data {
            workingDirectory file('runs/data')
            ideaModule "${rootProject.name}.${project.name}.main"
            args '--mod', mod_id, '--all', '--output', file('../Common/src/generated/resources/'), '--existing', file('src/main/resources/'), '--existing', file('/../Common/src/main/resources')
            taskName 'Data'
            mods {
                modDataRun {
                    source sourceSets.main
                }
            }
        }
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'

    annotationProcessor 'net.minecraftforge:eventbus-validator:7.0-beta.7'

    implementation('net.sf.jopt-simple:jopt-simple:5.0.4') { version { strictly '5.0.4' } }

    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:${mixinextras_version}"))
    implementation(jarJar("io.github.llamalad7:mixinextras-forge:${mixinextras_version}")) {
        jarJar.ranged(it, "[${mixinextras_version},)")
    }
}

mixin {
    config 'mixins.transmog.common.json'
    config 'mixins.transmog.forge.json'
}
jar {
    manifest {
        attributes([
                "MixinConfigs": "mixins.transmog.common.json,mixins.transmog.forge.json"
        ])
    }
    finalizedBy(tasks.jarJar)
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            fg.component(it)
        }
    }
}

sourceSets.each {
    def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
    it.output.resourcesDir = dir
    it.java.destinationDirectory = dir
}

curseforge {

    def curseforgeToken = System.getenv("CURSEFORGE_TOKEN")
    if (curseforgeToken) {
        apiKey = curseforgeToken
    }

    project {
        id = project.curseforge_project_id
        changelogType = "markdown"
        changelog = project.ext.changelog
        releaseType = project.release_type
        "${project.supported_versions}".split(',').each {
            addGameVersion "${it}"
        }
        addGameVersion "Forge"
        addGameVersion "Java 21"

        mainArtifact(tasks.jarJar) {
            displayName = "[Forge] Transmog $project.mod_version+$project.minecraft_version"
        }
        addArtifact(sourcesJar)
    }
}

modrinth {
    projectId = project.modrinth_project_id
    versionName = "[Forge] Transmog $project.mod_version+$project.minecraft_version"
    versionNumber = "forge-${project.mod_version}+${project.minecraft_version}"
    versionType = project.release_type
    changelog = project.ext.changelog
    uploadFile = tasks.jarJar
    additionalFiles = [sourcesJar]
    gameVersions = "${project.supported_versions}".split(',') as List<String>
    loaders = ["forge"]
}

sourceSets.each {
    def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
    it.output.resourcesDir = dir
    it.java.destinationDirectory = dir
}
