plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
    id "com.matthewprenger.cursegradle" version "1.4.+"
    id "com.modrinth.minotaur" version "2.+"
}

neoForge {
    version = neoforge_version

    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }

    parchment {
        minecraftVersion = parchment_minecraft_version
        mappingsVersion = parchment_mappings_version
    }

    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})"
        }
        client {
            client()
        }
        server {
            server()
        }
        data {
            data()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }

}

sourceSets.main.resources { srcDir 'src/generated/resources' }

curseforge {

    def curseforgeToken = System.getenv("CURSEFORGE_TOKEN")
    if (curseforgeToken) {
        apiKey = curseforgeToken
    }

    project {
        id = project.curseforge_project_id
        changelogType = "markdown"
        changelog = project.ext.changelog
        releaseType = project.release_type
        "${project.supported_versions}".split(',').each {
            addGameVersion "${it}"
        }
        addGameVersion "NeoForge"
        addGameVersion "Java 21"

        mainArtifact(tasks.jar) {
            displayName = "[NeoForge] Transmog $project.mod_version+$project.minecraft_version"
        }
        addArtifact(sourcesJar)
    }
}

modrinth {
    projectId = project.modrinth_project_id
    versionName = "[NeoForge] Transmog $project.mod_version+$project.minecraft_version"
    versionNumber = "neoforge-${project.mod_version}+${project.minecraft_version}"
    versionType = project.release_type
    changelog = project.ext.changelog
    uploadFile = jar
    additionalFiles = [sourcesJar]
    gameVersions = "${project.supported_versions}".split(',') as List<String>
    loaders = ["neoforge"]
}